//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPayServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UPayAuthNPurchaseRequest", Namespace="http://schemas.datacontract.org/2004/07/uPay.BusinessObjects")]
    public partial class UPayAuthNPurchaseRequest : object
    {
        
        private UPayServiceReference.UPayRequestHeader HeaderField;
        
        private UPayServiceReference.UPayRequestLine[] ListLineField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UPayServiceReference.UPayRequestHeader Header
        {
            get
            {
                return this.HeaderField;
            }
            set
            {
                this.HeaderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UPayServiceReference.UPayRequestLine[] ListLine
        {
            get
            {
                return this.ListLineField;
            }
            set
            {
                this.ListLineField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UPayRequestHeader", Namespace="http://schemas.datacontract.org/2004/07/uPay.BusinessObjects")]
    public partial class UPayRequestHeader : object
    {
        
        private string AddressLine1Field;
        
        private string AddressLine2Field;
        
        private string Batch_idField;
        
        private string Card_noField;
        
        private string CityField;
        
        private string CompanyField;
        
        private string CountryField;
        
        private string Cust_noField;
        
        private string Customer_nameField;
        
        private string Cvv_codeField;
        
        private string Email_idField;
        
        private string Expiry_MonthField;
        
        private string Expiry_YearField;
        
        private string Fax_noField;
        
        private string First_nameField;
        
        private string Invoice_noField;
        
        private string Is_testField;
        
        private string Last_nameField;
        
        private string LoginIDField;
        
        private string MerchantNameField;
        
        private string Merchant_keyField;
        
        private string Partial_AuthField;
        
        private string Phone_noField;
        
        private string ShippingZipcodeField;
        
        private string Split_tender_idField;
        
        private string StateField;
        
        private string Store_receiptField;
        
        private string TaxField;
        
        private string Total_amountField;
        
        private string Trans_idField;
        
        private string TransactionReferenceField;
        
        private string TransactionReference2Field;
        
        private string TypeField;
        
        private string ZipcodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine1
        {
            get
            {
                return this.AddressLine1Field;
            }
            set
            {
                this.AddressLine1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine2
        {
            get
            {
                return this.AddressLine2Field;
            }
            set
            {
                this.AddressLine2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Batch_id
        {
            get
            {
                return this.Batch_idField;
            }
            set
            {
                this.Batch_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Card_no
        {
            get
            {
                return this.Card_noField;
            }
            set
            {
                this.Card_noField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company
        {
            get
            {
                return this.CompanyField;
            }
            set
            {
                this.CompanyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cust_no
        {
            get
            {
                return this.Cust_noField;
            }
            set
            {
                this.Cust_noField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Customer_name
        {
            get
            {
                return this.Customer_nameField;
            }
            set
            {
                this.Customer_nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cvv_code
        {
            get
            {
                return this.Cvv_codeField;
            }
            set
            {
                this.Cvv_codeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email_id
        {
            get
            {
                return this.Email_idField;
            }
            set
            {
                this.Email_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Expiry_Month
        {
            get
            {
                return this.Expiry_MonthField;
            }
            set
            {
                this.Expiry_MonthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Expiry_Year
        {
            get
            {
                return this.Expiry_YearField;
            }
            set
            {
                this.Expiry_YearField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fax_no
        {
            get
            {
                return this.Fax_noField;
            }
            set
            {
                this.Fax_noField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string First_name
        {
            get
            {
                return this.First_nameField;
            }
            set
            {
                this.First_nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Invoice_no
        {
            get
            {
                return this.Invoice_noField;
            }
            set
            {
                this.Invoice_noField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Is_test
        {
            get
            {
                return this.Is_testField;
            }
            set
            {
                this.Is_testField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Last_name
        {
            get
            {
                return this.Last_nameField;
            }
            set
            {
                this.Last_nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginID
        {
            get
            {
                return this.LoginIDField;
            }
            set
            {
                this.LoginIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MerchantName
        {
            get
            {
                return this.MerchantNameField;
            }
            set
            {
                this.MerchantNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Merchant_key
        {
            get
            {
                return this.Merchant_keyField;
            }
            set
            {
                this.Merchant_keyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Partial_Auth
        {
            get
            {
                return this.Partial_AuthField;
            }
            set
            {
                this.Partial_AuthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone_no
        {
            get
            {
                return this.Phone_noField;
            }
            set
            {
                this.Phone_noField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShippingZipcode
        {
            get
            {
                return this.ShippingZipcodeField;
            }
            set
            {
                this.ShippingZipcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Split_tender_id
        {
            get
            {
                return this.Split_tender_idField;
            }
            set
            {
                this.Split_tender_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Store_receipt
        {
            get
            {
                return this.Store_receiptField;
            }
            set
            {
                this.Store_receiptField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tax
        {
            get
            {
                return this.TaxField;
            }
            set
            {
                this.TaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Total_amount
        {
            get
            {
                return this.Total_amountField;
            }
            set
            {
                this.Total_amountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Trans_id
        {
            get
            {
                return this.Trans_idField;
            }
            set
            {
                this.Trans_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionReference
        {
            get
            {
                return this.TransactionReferenceField;
            }
            set
            {
                this.TransactionReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionReference2
        {
            get
            {
                return this.TransactionReference2Field;
            }
            set
            {
                this.TransactionReference2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zipcode
        {
            get
            {
                return this.ZipcodeField;
            }
            set
            {
                this.ZipcodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UPayRequestLine", Namespace="http://schemas.datacontract.org/2004/07/uPay.BusinessObjects")]
    public partial class UPayRequestLine : object
    {
        
        private string ItemDescriptionField;
        
        private string ItemIDField;
        
        private string ItemNameField;
        
        private string ItemPriceField;
        
        private string ItemQuantityField;
        
        private string ItemTaxableField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemDescription
        {
            get
            {
                return this.ItemDescriptionField;
            }
            set
            {
                this.ItemDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemID
        {
            get
            {
                return this.ItemIDField;
            }
            set
            {
                this.ItemIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemName
        {
            get
            {
                return this.ItemNameField;
            }
            set
            {
                this.ItemNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemPrice
        {
            get
            {
                return this.ItemPriceField;
            }
            set
            {
                this.ItemPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemQuantity
        {
            get
            {
                return this.ItemQuantityField;
            }
            set
            {
                this.ItemQuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemTaxable
        {
            get
            {
                return this.ItemTaxableField;
            }
            set
            {
                this.ItemTaxableField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UPayResponse", Namespace="http://schemas.datacontract.org/2004/07/uPay.BusinessObjects")]
    public partial class UPayResponse : object
    {
        
        private string AccountNumberField;
        
        private string AddressField;
        
        private string AddressVerificationResultField;
        
        private string AuthorizationCodeField;
        
        private string AvsResponseField;
        
        private string BalanceOnCardField;
        
        private string CVVVerificationResultField;
        
        private string CardCodeResponseField;
        
        private string CardExpiryDateField;
        
        private string CardTypeField;
        
        private string CardholderAuthenticationVerificationField;
        
        private string CityField;
        
        private string CompanyField;
        
        private string CountryField;
        
        private string CustomerIDField;
        
        private string EmailAddressField;
        
        private string FaxField;
        
        private string FirstNameField;
        
        private string InvoiceNumberField;
        
        private string IsCommercialCardField;
        
        private string IsLevel3EligibleField;
        
        private string LastNameField;
        
        private string Level3DataField;
        
        private string NameOnCardVerificationResultField;
        
        private string PhoneField;
        
        private string ReasonCodeField;
        
        private string ReasonDescriptionField;
        
        private string RequestIdField;
        
        private string RequestedAmountField;
        
        private string ResponseCodeField;
        
        private string ReturnDescriptionField;
        
        private string ShippingZipCodeField;
        
        private string SplitTenderIDField;
        
        private string StateField;
        
        private string Store_receiptField;
        
        private string SubcodeField;
        
        private string TaxField;
        
        private string TokenKeyField;
        
        private string TotalAmountField;
        
        private string TransactionDateField;
        
        private string TransactionIDField;
        
        private string TransactionReferenceField;
        
        private string TransactionReference2Field;
        
        private string TransactionTimeField;
        
        private string TransactionTypeField;
        
        private string TransactionXMLField;
        
        private string UniPayTransactionUniqueIDField;
        
        private string ZipCodeField;
        
        private string ZipcodeVerificationResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber
        {
            get
            {
                return this.AccountNumberField;
            }
            set
            {
                this.AccountNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressVerificationResult
        {
            get
            {
                return this.AddressVerificationResultField;
            }
            set
            {
                this.AddressVerificationResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthorizationCode
        {
            get
            {
                return this.AuthorizationCodeField;
            }
            set
            {
                this.AuthorizationCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AvsResponse
        {
            get
            {
                return this.AvsResponseField;
            }
            set
            {
                this.AvsResponseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BalanceOnCard
        {
            get
            {
                return this.BalanceOnCardField;
            }
            set
            {
                this.BalanceOnCardField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CVVVerificationResult
        {
            get
            {
                return this.CVVVerificationResultField;
            }
            set
            {
                this.CVVVerificationResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardCodeResponse
        {
            get
            {
                return this.CardCodeResponseField;
            }
            set
            {
                this.CardCodeResponseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardExpiryDate
        {
            get
            {
                return this.CardExpiryDateField;
            }
            set
            {
                this.CardExpiryDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardType
        {
            get
            {
                return this.CardTypeField;
            }
            set
            {
                this.CardTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardholderAuthenticationVerification
        {
            get
            {
                return this.CardholderAuthenticationVerificationField;
            }
            set
            {
                this.CardholderAuthenticationVerificationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company
        {
            get
            {
                return this.CompanyField;
            }
            set
            {
                this.CompanyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerID
        {
            get
            {
                return this.CustomerIDField;
            }
            set
            {
                this.CustomerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress
        {
            get
            {
                return this.EmailAddressField;
            }
            set
            {
                this.EmailAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fax
        {
            get
            {
                return this.FaxField;
            }
            set
            {
                this.FaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceNumber
        {
            get
            {
                return this.InvoiceNumberField;
            }
            set
            {
                this.InvoiceNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsCommercialCard
        {
            get
            {
                return this.IsCommercialCardField;
            }
            set
            {
                this.IsCommercialCardField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsLevel3Eligible
        {
            get
            {
                return this.IsLevel3EligibleField;
            }
            set
            {
                this.IsLevel3EligibleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Level3Data
        {
            get
            {
                return this.Level3DataField;
            }
            set
            {
                this.Level3DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameOnCardVerificationResult
        {
            get
            {
                return this.NameOnCardVerificationResultField;
            }
            set
            {
                this.NameOnCardVerificationResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReasonCode
        {
            get
            {
                return this.ReasonCodeField;
            }
            set
            {
                this.ReasonCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReasonDescription
        {
            get
            {
                return this.ReasonDescriptionField;
            }
            set
            {
                this.ReasonDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestId
        {
            get
            {
                return this.RequestIdField;
            }
            set
            {
                this.RequestIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestedAmount
        {
            get
            {
                return this.RequestedAmountField;
            }
            set
            {
                this.RequestedAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseCode
        {
            get
            {
                return this.ResponseCodeField;
            }
            set
            {
                this.ResponseCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnDescription
        {
            get
            {
                return this.ReturnDescriptionField;
            }
            set
            {
                this.ReturnDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShippingZipCode
        {
            get
            {
                return this.ShippingZipCodeField;
            }
            set
            {
                this.ShippingZipCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SplitTenderID
        {
            get
            {
                return this.SplitTenderIDField;
            }
            set
            {
                this.SplitTenderIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Store_receipt
        {
            get
            {
                return this.Store_receiptField;
            }
            set
            {
                this.Store_receiptField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subcode
        {
            get
            {
                return this.SubcodeField;
            }
            set
            {
                this.SubcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tax
        {
            get
            {
                return this.TaxField;
            }
            set
            {
                this.TaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenKey
        {
            get
            {
                return this.TokenKeyField;
            }
            set
            {
                this.TokenKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TotalAmount
        {
            get
            {
                return this.TotalAmountField;
            }
            set
            {
                this.TotalAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionDate
        {
            get
            {
                return this.TransactionDateField;
            }
            set
            {
                this.TransactionDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionID
        {
            get
            {
                return this.TransactionIDField;
            }
            set
            {
                this.TransactionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionReference
        {
            get
            {
                return this.TransactionReferenceField;
            }
            set
            {
                this.TransactionReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionReference2
        {
            get
            {
                return this.TransactionReference2Field;
            }
            set
            {
                this.TransactionReference2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionTime
        {
            get
            {
                return this.TransactionTimeField;
            }
            set
            {
                this.TransactionTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionType
        {
            get
            {
                return this.TransactionTypeField;
            }
            set
            {
                this.TransactionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionXML
        {
            get
            {
                return this.TransactionXMLField;
            }
            set
            {
                this.TransactionXMLField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UniPayTransactionUniqueID
        {
            get
            {
                return this.UniPayTransactionUniqueIDField;
            }
            set
            {
                this.UniPayTransactionUniqueIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode
        {
            get
            {
                return this.ZipCodeField;
            }
            set
            {
                this.ZipCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipcodeVerificationResult
        {
            get
            {
                return this.ZipcodeVerificationResultField;
            }
            set
            {
                this.ZipcodeVerificationResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UPayAuthNPurchaseTokenRequest", Namespace="http://schemas.datacontract.org/2004/07/uPay.BusinessObjects")]
    public partial class UPayAuthNPurchaseTokenRequest : object
    {
        
        private string Batch_idField;
        
        private string Invoice_noField;
        
        private UPayServiceReference.UPayRequestLine[] ListLineField;
        
        private string MerchantNameField;
        
        private string ShippingZipcodeField;
        
        private string Store_receiptField;
        
        private string TaxField;
        
        private string TokenKeyField;
        
        private string Total_amountField;
        
        private string TransactionReferenceField;
        
        private string TransactionReference2Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Batch_id
        {
            get
            {
                return this.Batch_idField;
            }
            set
            {
                this.Batch_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Invoice_no
        {
            get
            {
                return this.Invoice_noField;
            }
            set
            {
                this.Invoice_noField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UPayServiceReference.UPayRequestLine[] ListLine
        {
            get
            {
                return this.ListLineField;
            }
            set
            {
                this.ListLineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MerchantName
        {
            get
            {
                return this.MerchantNameField;
            }
            set
            {
                this.MerchantNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShippingZipcode
        {
            get
            {
                return this.ShippingZipcodeField;
            }
            set
            {
                this.ShippingZipcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Store_receipt
        {
            get
            {
                return this.Store_receiptField;
            }
            set
            {
                this.Store_receiptField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tax
        {
            get
            {
                return this.TaxField;
            }
            set
            {
                this.TaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenKey
        {
            get
            {
                return this.TokenKeyField;
            }
            set
            {
                this.TokenKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Total_amount
        {
            get
            {
                return this.Total_amountField;
            }
            set
            {
                this.Total_amountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionReference
        {
            get
            {
                return this.TransactionReferenceField;
            }
            set
            {
                this.TransactionReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionReference2
        {
            get
            {
                return this.TransactionReference2Field;
            }
            set
            {
                this.TransactionReference2Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UPaySettlementRequest", Namespace="http://schemas.datacontract.org/2004/07/uPay.BusinessObjects")]
    public partial class UPaySettlementRequest : object
    {
        
        private string Batch_idField;
        
        private string Invoice_noField;
        
        private string Request_idField;
        
        private string ShippingZipcodeField;
        
        private string Store_receiptField;
        
        private string TaxField;
        
        private string Total_amountField;
        
        private string Trans_idField;
        
        private string TransactionReferenceField;
        
        private string TransactionReference2Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Batch_id
        {
            get
            {
                return this.Batch_idField;
            }
            set
            {
                this.Batch_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Invoice_no
        {
            get
            {
                return this.Invoice_noField;
            }
            set
            {
                this.Invoice_noField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Request_id
        {
            get
            {
                return this.Request_idField;
            }
            set
            {
                this.Request_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShippingZipcode
        {
            get
            {
                return this.ShippingZipcodeField;
            }
            set
            {
                this.ShippingZipcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Store_receipt
        {
            get
            {
                return this.Store_receiptField;
            }
            set
            {
                this.Store_receiptField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tax
        {
            get
            {
                return this.TaxField;
            }
            set
            {
                this.TaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Total_amount
        {
            get
            {
                return this.Total_amountField;
            }
            set
            {
                this.Total_amountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Trans_id
        {
            get
            {
                return this.Trans_idField;
            }
            set
            {
                this.Trans_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionReference
        {
            get
            {
                return this.TransactionReferenceField;
            }
            set
            {
                this.TransactionReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionReference2
        {
            get
            {
                return this.TransactionReference2Field;
            }
            set
            {
                this.TransactionReference2Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UPaySettlementRequestForLevel3", Namespace="http://schemas.datacontract.org/2004/07/uPay.BusinessObjects")]
    public partial class UPaySettlementRequestForLevel3 : object
    {
        
        private string Batch_idField;
        
        private string CardTypeField;
        
        private string Customer_nameField;
        
        private bool EligibleToSendLevel2DataField;
        
        private bool EligibleToSendLevel3DataField;
        
        private string Invoice_noField;
        
        private UPayServiceReference.UPayRequestLevel2Detail Level2DetailField;
        
        private UPayServiceReference.UPayRequestLevel3Detail[] Level3DetailsField;
        
        private string Request_idField;
        
        private string ShippingAddressLine1Field;
        
        private string ShippingAddressLine2Field;
        
        private string ShippingCityField;
        
        private string ShippingStateField;
        
        private string ShippingZipcodeField;
        
        private string Store_receiptField;
        
        private string TaxField;
        
        private string Total_amountField;
        
        private string Trans_idField;
        
        private string TransactionReferenceField;
        
        private string TransactionReference2Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Batch_id
        {
            get
            {
                return this.Batch_idField;
            }
            set
            {
                this.Batch_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardType
        {
            get
            {
                return this.CardTypeField;
            }
            set
            {
                this.CardTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Customer_name
        {
            get
            {
                return this.Customer_nameField;
            }
            set
            {
                this.Customer_nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EligibleToSendLevel2Data
        {
            get
            {
                return this.EligibleToSendLevel2DataField;
            }
            set
            {
                this.EligibleToSendLevel2DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EligibleToSendLevel3Data
        {
            get
            {
                return this.EligibleToSendLevel3DataField;
            }
            set
            {
                this.EligibleToSendLevel3DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Invoice_no
        {
            get
            {
                return this.Invoice_noField;
            }
            set
            {
                this.Invoice_noField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UPayServiceReference.UPayRequestLevel2Detail Level2Detail
        {
            get
            {
                return this.Level2DetailField;
            }
            set
            {
                this.Level2DetailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UPayServiceReference.UPayRequestLevel3Detail[] Level3Details
        {
            get
            {
                return this.Level3DetailsField;
            }
            set
            {
                this.Level3DetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Request_id
        {
            get
            {
                return this.Request_idField;
            }
            set
            {
                this.Request_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShippingAddressLine1
        {
            get
            {
                return this.ShippingAddressLine1Field;
            }
            set
            {
                this.ShippingAddressLine1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShippingAddressLine2
        {
            get
            {
                return this.ShippingAddressLine2Field;
            }
            set
            {
                this.ShippingAddressLine2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShippingCity
        {
            get
            {
                return this.ShippingCityField;
            }
            set
            {
                this.ShippingCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShippingState
        {
            get
            {
                return this.ShippingStateField;
            }
            set
            {
                this.ShippingStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShippingZipcode
        {
            get
            {
                return this.ShippingZipcodeField;
            }
            set
            {
                this.ShippingZipcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Store_receipt
        {
            get
            {
                return this.Store_receiptField;
            }
            set
            {
                this.Store_receiptField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tax
        {
            get
            {
                return this.TaxField;
            }
            set
            {
                this.TaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Total_amount
        {
            get
            {
                return this.Total_amountField;
            }
            set
            {
                this.Total_amountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Trans_id
        {
            get
            {
                return this.Trans_idField;
            }
            set
            {
                this.Trans_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionReference
        {
            get
            {
                return this.TransactionReferenceField;
            }
            set
            {
                this.TransactionReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionReference2
        {
            get
            {
                return this.TransactionReference2Field;
            }
            set
            {
                this.TransactionReference2Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UPayRequestLevel2Detail", Namespace="http://schemas.datacontract.org/2004/07/uPay.BusinessObjects")]
    public partial class UPayRequestLevel2Detail : object
    {
        
        private string L2AlternateTaxAmountField;
        
        private string L2AlternateTaxIndicatorField;
        
        private string L2DestinationCountryCodeField;
        
        private string L2DiscountAmountField;
        
        private string L2DutyAmountField;
        
        private string L2FVATtaxAmountField;
        
        private string L2FreightAmountField;
        
        private string L2ShipFromZipField;
        
        private string L2VATtaxRateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string L2AlternateTaxAmount
        {
            get
            {
                return this.L2AlternateTaxAmountField;
            }
            set
            {
                this.L2AlternateTaxAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string L2AlternateTaxIndicator
        {
            get
            {
                return this.L2AlternateTaxIndicatorField;
            }
            set
            {
                this.L2AlternateTaxIndicatorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string L2DestinationCountryCode
        {
            get
            {
                return this.L2DestinationCountryCodeField;
            }
            set
            {
                this.L2DestinationCountryCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string L2DiscountAmount
        {
            get
            {
                return this.L2DiscountAmountField;
            }
            set
            {
                this.L2DiscountAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string L2DutyAmount
        {
            get
            {
                return this.L2DutyAmountField;
            }
            set
            {
                this.L2DutyAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string L2FVATtaxAmount
        {
            get
            {
                return this.L2FVATtaxAmountField;
            }
            set
            {
                this.L2FVATtaxAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string L2FreightAmount
        {
            get
            {
                return this.L2FreightAmountField;
            }
            set
            {
                this.L2FreightAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string L2ShipFromZip
        {
            get
            {
                return this.L2ShipFromZipField;
            }
            set
            {
                this.L2ShipFromZipField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string L2VATtaxRate
        {
            get
            {
                return this.L2VATtaxRateField;
            }
            set
            {
                this.L2VATtaxRateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UPayRequestLevel3Detail", Namespace="http://schemas.datacontract.org/2004/07/uPay.BusinessObjects")]
    public partial class UPayRequestLevel3Detail : object
    {
        
        private string L3ItemCommodityCodeField;
        
        private string L3ItemDebitIndicatorField;
        
        private string L3ItemDescriptionField;
        
        private string L3ItemDiscountField;
        
        private string L3ItemDiscountRateField;
        
        private string L3ItemDiscountedIndicatorField;
        
        private string L3ItemLineTotalField;
        
        private string L3ItemQuantityField;
        
        private string L3ItemTaxAmountField;
        
        private string L3ItemTaxRateField;
        
        private string L3ItemUnitCostField;
        
        private string L3ItemUnitOfMeasureField;
        
        private string L3LineItemNameField;
        
        private string L3TaxTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string L3ItemCommodityCode
        {
            get
            {
                return this.L3ItemCommodityCodeField;
            }
            set
            {
                this.L3ItemCommodityCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string L3ItemDebitIndicator
        {
            get
            {
                return this.L3ItemDebitIndicatorField;
            }
            set
            {
                this.L3ItemDebitIndicatorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string L3ItemDescription
        {
            get
            {
                return this.L3ItemDescriptionField;
            }
            set
            {
                this.L3ItemDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string L3ItemDiscount
        {
            get
            {
                return this.L3ItemDiscountField;
            }
            set
            {
                this.L3ItemDiscountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string L3ItemDiscountRate
        {
            get
            {
                return this.L3ItemDiscountRateField;
            }
            set
            {
                this.L3ItemDiscountRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string L3ItemDiscountedIndicator
        {
            get
            {
                return this.L3ItemDiscountedIndicatorField;
            }
            set
            {
                this.L3ItemDiscountedIndicatorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string L3ItemLineTotal
        {
            get
            {
                return this.L3ItemLineTotalField;
            }
            set
            {
                this.L3ItemLineTotalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string L3ItemQuantity
        {
            get
            {
                return this.L3ItemQuantityField;
            }
            set
            {
                this.L3ItemQuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string L3ItemTaxAmount
        {
            get
            {
                return this.L3ItemTaxAmountField;
            }
            set
            {
                this.L3ItemTaxAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string L3ItemTaxRate
        {
            get
            {
                return this.L3ItemTaxRateField;
            }
            set
            {
                this.L3ItemTaxRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string L3ItemUnitCost
        {
            get
            {
                return this.L3ItemUnitCostField;
            }
            set
            {
                this.L3ItemUnitCostField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string L3ItemUnitOfMeasure
        {
            get
            {
                return this.L3ItemUnitOfMeasureField;
            }
            set
            {
                this.L3ItemUnitOfMeasureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string L3LineItemName
        {
            get
            {
                return this.L3LineItemNameField;
            }
            set
            {
                this.L3LineItemNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string L3TaxType
        {
            get
            {
                return this.L3TaxTypeField;
            }
            set
            {
                this.L3TaxTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UPayVoidRequest", Namespace="http://schemas.datacontract.org/2004/07/uPay.BusinessObjects")]
    public partial class UPayVoidRequest : object
    {
        
        private string Batch_idField;
        
        private string Invoice_noField;
        
        private string Request_idField;
        
        private string Store_receiptField;
        
        private string Total_amountField;
        
        private string Trans_idField;
        
        private string TransactionReferenceField;
        
        private string TransactionReference2Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Batch_id
        {
            get
            {
                return this.Batch_idField;
            }
            set
            {
                this.Batch_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Invoice_no
        {
            get
            {
                return this.Invoice_noField;
            }
            set
            {
                this.Invoice_noField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Request_id
        {
            get
            {
                return this.Request_idField;
            }
            set
            {
                this.Request_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Store_receipt
        {
            get
            {
                return this.Store_receiptField;
            }
            set
            {
                this.Store_receiptField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Total_amount
        {
            get
            {
                return this.Total_amountField;
            }
            set
            {
                this.Total_amountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Trans_id
        {
            get
            {
                return this.Trans_idField;
            }
            set
            {
                this.Trans_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionReference
        {
            get
            {
                return this.TransactionReferenceField;
            }
            set
            {
                this.TransactionReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionReference2
        {
            get
            {
                return this.TransactionReference2Field;
            }
            set
            {
                this.TransactionReference2Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UPayRefundRequest", Namespace="http://schemas.datacontract.org/2004/07/uPay.BusinessObjects")]
    public partial class UPayRefundRequest : object
    {
        
        private string Batch_idField;
        
        private string Invoice_noField;
        
        private string Request_idField;
        
        private string Store_receiptField;
        
        private string Total_amountField;
        
        private string Trans_idField;
        
        private string TransactionReferenceField;
        
        private string TransactionReference2Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Batch_id
        {
            get
            {
                return this.Batch_idField;
            }
            set
            {
                this.Batch_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Invoice_no
        {
            get
            {
                return this.Invoice_noField;
            }
            set
            {
                this.Invoice_noField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Request_id
        {
            get
            {
                return this.Request_idField;
            }
            set
            {
                this.Request_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Store_receipt
        {
            get
            {
                return this.Store_receiptField;
            }
            set
            {
                this.Store_receiptField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Total_amount
        {
            get
            {
                return this.Total_amountField;
            }
            set
            {
                this.Total_amountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Trans_id
        {
            get
            {
                return this.Trans_idField;
            }
            set
            {
                this.Trans_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionReference
        {
            get
            {
                return this.TransactionReferenceField;
            }
            set
            {
                this.TransactionReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionReference2
        {
            get
            {
                return this.TransactionReference2Field;
            }
            set
            {
                this.TransactionReference2Field = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UPayServiceReference.ITransactionService")]
    public interface ITransactionService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransactionService/CreateTokenAndAuthorize", ReplyAction="http://tempuri.org/ITransactionService/CreateTokenAndAuthorizeResponse")]
        System.Threading.Tasks.Task<UPayServiceReference.UPayResponse> CreateTokenAndAuthorizeAsync(string sBUKey, UPayServiceReference.UPayAuthNPurchaseRequest uPayRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransactionService/ProcessAuthorization", ReplyAction="http://tempuri.org/ITransactionService/ProcessAuthorizationResponse")]
        System.Threading.Tasks.Task<UPayServiceReference.UPayResponse> ProcessAuthorizationAsync(string sBUKey, UPayServiceReference.UPayAuthNPurchaseRequest uPayRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransactionService/ProcessAuthorizationWithToken", ReplyAction="http://tempuri.org/ITransactionService/ProcessAuthorizationWithTokenResponse")]
        System.Threading.Tasks.Task<UPayServiceReference.UPayResponse> ProcessAuthorizationWithTokenAsync(string sBUKey, UPayServiceReference.UPayAuthNPurchaseTokenRequest uPayRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransactionService/ProcessSettlement", ReplyAction="http://tempuri.org/ITransactionService/ProcessSettlementResponse")]
        System.Threading.Tasks.Task<UPayServiceReference.UPayResponse> ProcessSettlementAsync(string sBUKey, UPayServiceReference.UPaySettlementRequest uPayRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransactionService/ProcessL3Settlement", ReplyAction="http://tempuri.org/ITransactionService/ProcessL3SettlementResponse")]
        System.Threading.Tasks.Task<UPayServiceReference.UPayResponse> ProcessL3SettlementAsync(string sBUKey, UPayServiceReference.UPaySettlementRequestForLevel3 uPayRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransactionService/ProcessVoid", ReplyAction="http://tempuri.org/ITransactionService/ProcessVoidResponse")]
        System.Threading.Tasks.Task<UPayServiceReference.UPayResponse> ProcessVoidAsync(string sBUKey, UPayServiceReference.UPayVoidRequest uPayRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransactionService/ProcessRefund", ReplyAction="http://tempuri.org/ITransactionService/ProcessRefundResponse")]
        System.Threading.Tasks.Task<UPayServiceReference.UPayResponse> ProcessRefundAsync(string sBUKey, UPayServiceReference.UPayRefundRequest uPayRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransactionService/CreateTokenAndPurchase", ReplyAction="http://tempuri.org/ITransactionService/CreateTokenAndPurchaseResponse")]
        System.Threading.Tasks.Task<UPayServiceReference.UPayResponse> CreateTokenAndPurchaseAsync(string sBUKey, UPayServiceReference.UPayAuthNPurchaseRequest uPayRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransactionService/ProcessPurchase", ReplyAction="http://tempuri.org/ITransactionService/ProcessPurchaseResponse")]
        System.Threading.Tasks.Task<UPayServiceReference.UPayResponse> ProcessPurchaseAsync(string sBUKey, UPayServiceReference.UPayAuthNPurchaseRequest uPayRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransactionService/ProcessPurchaseWithToken", ReplyAction="http://tempuri.org/ITransactionService/ProcessPurchaseWithTokenResponse")]
        System.Threading.Tasks.Task<UPayServiceReference.UPayResponse> ProcessPurchaseWithTokenAsync(string sBUKey, UPayServiceReference.UPayAuthNPurchaseTokenRequest uPayRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransactionService/UpdateExternalOrderNumber", ReplyAction="http://tempuri.org/ITransactionService/UpdateExternalOrderNumberResponse")]
        System.Threading.Tasks.Task<bool> UpdateExternalOrderNumberAsync(string sBUKey, string sRequestId, string sOrderNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransactionService/SetSettlementPartial", ReplyAction="http://tempuri.org/ITransactionService/SetSettlementPartialResponse")]
        System.Threading.Tasks.Task<bool> SetSettlementPartialAsync(string sBUKey, string sRequestId, string sOrderNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransactionService/SetSettlementComplete", ReplyAction="http://tempuri.org/ITransactionService/SetSettlementCompleteResponse")]
        System.Threading.Tasks.Task<bool> SetSettlementCompleteAsync(string sBUKey, string sRequestId, string sOrderNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransactionService/GetCreditCardToken", ReplyAction="http://tempuri.org/ITransactionService/GetCreditCardTokenResponse")]
        System.Threading.Tasks.Task<string> GetCreditCardTokenAsync(string sBUKey, string sRequestId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransactionService/GetCreditCardDetail", ReplyAction="http://tempuri.org/ITransactionService/GetCreditCardDetailResponse")]
        System.Threading.Tasks.Task<UPayServiceReference.UPayResponse> GetCreditCardDetailAsync(string sBUKey, string sRequestId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransactionService/UpdateCreditCardDetail", ReplyAction="http://tempuri.org/ITransactionService/UpdateCreditCardDetailResponse")]
        System.Threading.Tasks.Task<UPayServiceReference.UPayResponse> UpdateCreditCardDetailAsync(string sBUKey, UPayServiceReference.UPayAuthNPurchaseRequest uPayRequest, string sRequestId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface ITransactionServiceChannel : UPayServiceReference.ITransactionService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class TransactionServiceClient : System.ServiceModel.ClientBase<UPayServiceReference.ITransactionService>, UPayServiceReference.ITransactionService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TransactionServiceClient() : 
                base(TransactionServiceClient.GetDefaultBinding(), TransactionServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ITransactionService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TransactionServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(TransactionServiceClient.GetBindingForEndpoint(endpointConfiguration), TransactionServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TransactionServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TransactionServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TransactionServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TransactionServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TransactionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<UPayServiceReference.UPayResponse> CreateTokenAndAuthorizeAsync(string sBUKey, UPayServiceReference.UPayAuthNPurchaseRequest uPayRequest)
        {
            return base.Channel.CreateTokenAndAuthorizeAsync(sBUKey, uPayRequest);
        }
        
        public System.Threading.Tasks.Task<UPayServiceReference.UPayResponse> ProcessAuthorizationAsync(string sBUKey, UPayServiceReference.UPayAuthNPurchaseRequest uPayRequest)
        {
            return base.Channel.ProcessAuthorizationAsync(sBUKey, uPayRequest);
        }
        
        public System.Threading.Tasks.Task<UPayServiceReference.UPayResponse> ProcessAuthorizationWithTokenAsync(string sBUKey, UPayServiceReference.UPayAuthNPurchaseTokenRequest uPayRequest)
        {
            return base.Channel.ProcessAuthorizationWithTokenAsync(sBUKey, uPayRequest);
        }
        
        public System.Threading.Tasks.Task<UPayServiceReference.UPayResponse> ProcessSettlementAsync(string sBUKey, UPayServiceReference.UPaySettlementRequest uPayRequest)
        {
            return base.Channel.ProcessSettlementAsync(sBUKey, uPayRequest);
        }
        
        public System.Threading.Tasks.Task<UPayServiceReference.UPayResponse> ProcessL3SettlementAsync(string sBUKey, UPayServiceReference.UPaySettlementRequestForLevel3 uPayRequest)
        {
            return base.Channel.ProcessL3SettlementAsync(sBUKey, uPayRequest);
        }
        
        public System.Threading.Tasks.Task<UPayServiceReference.UPayResponse> ProcessVoidAsync(string sBUKey, UPayServiceReference.UPayVoidRequest uPayRequest)
        {
            return base.Channel.ProcessVoidAsync(sBUKey, uPayRequest);
        }
        
        public System.Threading.Tasks.Task<UPayServiceReference.UPayResponse> ProcessRefundAsync(string sBUKey, UPayServiceReference.UPayRefundRequest uPayRequest)
        {
            return base.Channel.ProcessRefundAsync(sBUKey, uPayRequest);
        }
        
        public System.Threading.Tasks.Task<UPayServiceReference.UPayResponse> CreateTokenAndPurchaseAsync(string sBUKey, UPayServiceReference.UPayAuthNPurchaseRequest uPayRequest)
        {
            return base.Channel.CreateTokenAndPurchaseAsync(sBUKey, uPayRequest);
        }
        
        public System.Threading.Tasks.Task<UPayServiceReference.UPayResponse> ProcessPurchaseAsync(string sBUKey, UPayServiceReference.UPayAuthNPurchaseRequest uPayRequest)
        {
            return base.Channel.ProcessPurchaseAsync(sBUKey, uPayRequest);
        }
        
        public System.Threading.Tasks.Task<UPayServiceReference.UPayResponse> ProcessPurchaseWithTokenAsync(string sBUKey, UPayServiceReference.UPayAuthNPurchaseTokenRequest uPayRequest)
        {
            return base.Channel.ProcessPurchaseWithTokenAsync(sBUKey, uPayRequest);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateExternalOrderNumberAsync(string sBUKey, string sRequestId, string sOrderNumber)
        {
            return base.Channel.UpdateExternalOrderNumberAsync(sBUKey, sRequestId, sOrderNumber);
        }
        
        public System.Threading.Tasks.Task<bool> SetSettlementPartialAsync(string sBUKey, string sRequestId, string sOrderNumber)
        {
            return base.Channel.SetSettlementPartialAsync(sBUKey, sRequestId, sOrderNumber);
        }
        
        public System.Threading.Tasks.Task<bool> SetSettlementCompleteAsync(string sBUKey, string sRequestId, string sOrderNumber)
        {
            return base.Channel.SetSettlementCompleteAsync(sBUKey, sRequestId, sOrderNumber);
        }
        
        public System.Threading.Tasks.Task<string> GetCreditCardTokenAsync(string sBUKey, string sRequestId)
        {
            return base.Channel.GetCreditCardTokenAsync(sBUKey, sRequestId);
        }
        
        public System.Threading.Tasks.Task<UPayServiceReference.UPayResponse> GetCreditCardDetailAsync(string sBUKey, string sRequestId)
        {
            return base.Channel.GetCreditCardDetailAsync(sBUKey, sRequestId);
        }
        
        public System.Threading.Tasks.Task<UPayServiceReference.UPayResponse> UpdateCreditCardDetailAsync(string sBUKey, UPayServiceReference.UPayAuthNPurchaseRequest uPayRequest, string sRequestId)
        {
            return base.Channel.UpdateCreditCardDetailAsync(sBUKey, uPayRequest, sRequestId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ITransactionService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ITransactionService))
            {
                return new System.ServiceModel.EndpointAddress("http://10.10.17.8:5556/TransactionService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return TransactionServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ITransactionService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return TransactionServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ITransactionService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ITransactionService,
        }
    }
}
